services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    container_name: user-service
    networks:
      - micro_net

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    container_name: product-service
    networks:
      - micro_net

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
    container_name: order-service
    networks:
      - micro_net

networks:
  micro_net:
    driver: bridge
