apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: proyectv1
build:
  artifacts:
    - image: checo10/user-service
      context: user-service
    - image: checo10/product-service
      context: product-service
    - image: checo10/order-service
      context: order-service
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
